import { User } from "@/components/UserList";

export const users: User[] = [
  {
    id: "1",
    name: "Alice Johnson",
    avatarUrl: "/file.svg",
    lastMessage: "Hey, how are you?",
    lastMessageTime: "09:15 AM",
    status: "online",
    unreadCount: 2,
  },
  {
    id: "2",
    name: "Bob Smith",
    avatarUrl: "/globe.svg",
    lastMessage: "See you at the meeting.",
    lastMessageTime: "08:45 AM",
    status: "offline",
    unreadCount: 0,
  },
  {
    id: "3",
    name: "Charlie Group",
    isGroup: true,
    avatarUrl: "/next.svg",
    lastMessage: "Let's finalize the project.",
    lastMessageTime: "Yesterday",
    groupMembers: ["Alice Johnson", "Bob Smith", "Diana Prince"],
    unreadCount: 5,
  },
  {
    id: "4",
    name: "Diana Prince",
    avatarUrl: "/vercel.svg",
    lastMessage: "Typing...",
    lastMessageTime: "07:30 AM",
    status: "typing...",
    unreadCount: 1,
  },
  {
    id: "5",
    name: "Eve Group",
    isGroup: true,
    avatarUrl: "/window.svg",
    lastMessage: "Welcome to the group!",
    lastMessageTime: "Monday",
    groupMembers: ["Eve Adams", "Frank Lee"],
    unreadCount: 0,
  },
  {
    id: "6",
    name: "Frank Lee",
    avatarUrl: "/file.svg",
    lastMessage: "Let's catch up soon!",
    lastMessageTime: "08:10 AM",
    status: "online",
    unreadCount: 0,
  },
  {
    id: "7",
    name: "Grace Hopper",
    avatarUrl: "/globe.svg",
    lastMessage: "I'll send the report.",
    lastMessageTime: "Yesterday",
    status: "offline",
    unreadCount: 1,
  },
  {
    id: "8",
    name: "Henry Ford",
    avatarUrl: "/next.svg",
    lastMessage: "Meeting at 3pm.",
    lastMessageTime: "Yesterday",
    status: "online",
    unreadCount: 0,
  },
  {
    id: "9",
    name: "Ivy Group",
    isGroup: true,
    avatarUrl: "/vercel.svg",
    lastMessage: "Shared the document.",
    lastMessageTime: "Monday",
    groupMembers: ["Grace Hopper", "Frank Lee", "Henry Ford"],
    unreadCount: 2,
  },
  {
    id: "10",
    name: "Jack Ma",
    avatarUrl: "/window.svg",
    lastMessage: "Thanks!",
    lastMessageTime: "Sunday",
    status: "offline",
    unreadCount: 0,
  },
  {
    id: "11",
    name: "Karen Page",
    avatarUrl: "/file.svg",
    lastMessage: "See you tomorrow.",
    lastMessageTime: "Sunday",
    status: "online",
    unreadCount: 3,
  },
  {
    id: "12",
    name: "Leo Messi",
    avatarUrl: "/globe.svg",
    lastMessage: "Goal!",
    lastMessageTime: "Saturday",
    status: "online",
    unreadCount: 0,
  },
  {
    id: "13",
    name: "Mona Lisa",
    avatarUrl: "/next.svg",
    lastMessage: "Nice to meet you!",
    lastMessageTime: "Saturday",
    status: "offline",
    unreadCount: 0,
  },
  {
    id: "14",
    name: "Nina Simone",
    avatarUrl: "/vercel.svg",
    lastMessage: "Let's sing together.",
    lastMessageTime: "Friday",
    status: "online",
    unreadCount: 1,
  },
  {
    id: "15",
    name: "Oscar Wilde",
    avatarUrl: "/window.svg",
    lastMessage: "Witty as always!",
    lastMessageTime: "Friday",
    status: "offline",
    unreadCount: 0,
  },
  {
    id: "16",
    name: "Penny Group",
    isGroup: true,
    avatarUrl: "/file.svg",
    lastMessage: "Welcome Penny!",
    lastMessageTime: "Thursday",
    groupMembers: ["Oscar Wilde", "Nina Simone", "Mona Lisa"],
    unreadCount: 4,
  },
  {
    id: "17",
    name: "Quentin Tarantino",
    avatarUrl: "/globe.svg",
    lastMessage: "Movie night?",
    lastMessageTime: "Thursday",
    status: "online",
    unreadCount: 0,
  },
  {
    id: "18",
    name: "Rachel Green",
    avatarUrl: "/next.svg",
    lastMessage: "Coffee at Central Perk?",
    lastMessageTime: "Wednesday",
    status: "offline",
    unreadCount: 2,
  },
  {
    id: "19",
    name: "Steve Jobs",
    avatarUrl: "/vercel.svg",
    lastMessage: "Innovation!",
    lastMessageTime: "Wednesday",
    status: "online",
    unreadCount: 0,
  },
  {
    id: "20",
    name: "Tina Fey",
    avatarUrl: "/window.svg",
    lastMessage: "Let's write!",
    lastMessageTime: "Tuesday",
    status: "offline",
    unreadCount: 0,
  },
  {
    id: "21",
    name: "Uma Thurman",
    avatarUrl: "/file.svg",
    lastMessage: "Ready for action!",
    lastMessageTime: "Tuesday",
    status: "online",
    unreadCount: 1,
  },
  {
    id: "22",
    name: "Victor Hugo",
    avatarUrl: "/globe.svg",
    lastMessage: "Reading Les Misérables.",
    lastMessageTime: "Monday",
    status: "offline",
    unreadCount: 0,
  },
  {
    id: "23",
    name: "Wendy Darling",
    avatarUrl: "/next.svg",
    lastMessage: "Neverland awaits!",
    lastMessageTime: "Monday",
    status: "online",
    unreadCount: 0,
  },
  {
    id: "24",
    name: "Xander Cage",
    avatarUrl: "/vercel.svg",
    lastMessage: "Extreme sports!",
    lastMessageTime: "Sunday",
    status: "offline",
    unreadCount: 0,
  },
  {
    id: "25",
    name: "Yara Shahidi",
    avatarUrl: "/window.svg",
    lastMessage: "See you at the event.",
    lastMessageTime: "Sunday",
    status: "online",
    unreadCount: 2,
  },
  {
    id: "26",
    name: "Zane Malik",
    avatarUrl: "/file.svg",
    lastMessage: "Singing now!",
    lastMessageTime: "Saturday",
    status: "offline",
    unreadCount: 0,
  },
  {
    id: "27",
    name: "Alpha Group",
    isGroup: true,
    avatarUrl: "/globe.svg",
    lastMessage: "Alpha team assembled.",
    lastMessageTime: "Friday",
    groupMembers: ["Zane Malik", "Yara Shahidi", "Xander Cage"],
    unreadCount: 3,
  },
  {
    id: "28",
    name: "Beta Group",
    isGroup: true,
    avatarUrl: "/next.svg",
    lastMessage: "Beta test complete.",
    lastMessageTime: "Thursday",
    groupMembers: ["Wendy Darling", "Victor Hugo", "Uma Thurman"],
    unreadCount: 0,
  },
  {
    id: "29",
    name: "Gamma Group",
    isGroup: true,
    avatarUrl: "/vercel.svg",
    lastMessage: "Gamma rays detected!",
    lastMessageTime: "Wednesday",
    groupMembers: ["Tina Fey", "Steve Jobs", "Rachel Green"],
    unreadCount: 1,
  },
  {
    id: "30",
    name: "Delta Group",
    isGroup: true,
    avatarUrl: "/window.svg",
    lastMessage: "Delta update released.",
    lastMessageTime: "Tuesday",
    groupMembers: ["Quentin Tarantino", "Penny Group", "Oscar Wilde"],
    unreadCount: 0,
  },
  {
    id: "31",
    name: "Epsilon Group",
    isGroup: true,
    avatarUrl: "/file.svg",
    lastMessage: "Epsilon is live!",
    lastMessageTime: "Monday",
    groupMembers: ["Nina Simone", "Mona Lisa", "Leo Messi"],
    unreadCount: 2,
  },
  {
    id: "32",
    name: "Fiona Apple",
    avatarUrl: "/globe.svg",
    lastMessage: "Music session?",
    lastMessageTime: "Sunday",
    status: "online",
    unreadCount: 0,
  },
  {
    id: "33",
    name: "George Clooney",
    avatarUrl: "/next.svg",
    lastMessage: "Coffee break!",
    lastMessageTime: "Saturday",
    status: "offline",
    unreadCount: 0,
  },
  {
    id: "34",
    name: "Hannah Montana",
    avatarUrl: "/vercel.svg",
    lastMessage: "Best of both worlds!",
    lastMessageTime: "Friday",
    status: "online",
    unreadCount: 1,
  },
  {
    id: "35",
    name: "Ian McKellen",
    avatarUrl: "/window.svg",
    lastMessage: "You shall not pass!",
    lastMessageTime: "Thursday",
    status: "offline",
    unreadCount: 0,
  },
];
